spring:
  application:
    # 应用名称
    name: order
  # 数据库配置
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: guochen
      password: guochen
      url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    # 打印SQL
    show-sql: true
#eureka:
#  client:
#    service-url:
#      # eureka注册地址
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    # 向eureka注册真实ip设置
#    prefer-ip-address: true
#    # 起一个别名
##   hostname: kanxue
env:
  test33
girl:
  name: guocenkanxue
  age: 16
